# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
  adapter: postgresql
  database: project_development
  pool: 5
  timeout: 5000
  # username: niall
  # password: anfield

test: &TEST
  adapter: postgresql
  database: project_test
  pool: 5
  timeout: 5000
  # username: niall
  # password: anfield

production:
  adapter: postgresql
  database: project_production
  pool: 5
  timeout: 5000
  # username: niall
  # password: anfield


cucumber:
  <<: *TEST
